name: CI

on: push

jobs:
  e2e-test:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@b7c009e73c3431cb9c18e3e6267fa1f04792dbf2 # v2.2.4
    with:
      hosting-provider: cloudflare
