name: CI

on: push

jobs:
  e2e-test:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@d09c4898d1681a64b001e86e2327f1aa7a772422 # v2.3.1
    with:
      hosting-provider: cloudflare
