name: CI

on: push

jobs:
  e2e-test:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@33108f25a71d0f30636b531223a62692a9559601 # v2.4.2
    with:
      hosting-provider: cloudflare
