name: CI

on: push

jobs:
  e2e-test:
    uses: jill64/playwright-config/.github/workflows/duplex-playwright.yml@c5b02b99d0d7b9725a10ccf14579da07cceaedab # v2.2.6
    with:
      hosting-provider: cloudflare
