name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    uses: jill64/reusable-workflow/.github/workflows/publish-npm.yml@main
    with:
      pre-publish: pnpm build:adapter
    secrets: inherit
