name: Release

on:
  push:
    branches: main

jobs:
  release:
    uses: jill64/semantic-manager/.github/workflows/release-npm.yml@main
    with:
      pre-publish: pnpm build:lib
    secrets: inherit
